# Generated by Django 5.2.3 on 2025-07-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=40)),
                ('phone', models.IntegerField(default=0, max_length=11)),
                ('desc', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
