# Generated by Django 5.2.3 on 2025-07-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=0, max_length=6),
        ),
        migrations.AlterField(
            model_name='orders',
            name='zipcode',
            field=models.CharField(default=0),
        ),
    ]
