# Generated by Django 5.2.3 on 2025-07-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_orderupdate_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderupdate',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='orderupdate',
            name='update_desc',
        ),
    ]
