# Generated by Django 5.2.3 on 2025-07-21 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_orderupdate_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderupdate',
            name='update_desc',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
